### ISSUE TITLE
vote/Id.module.scss

### ISSUE THREAD

**Issue by auhy49** [STFExSavle/with-savle#81]
```css
.favorite_comment_share {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-top: 20px;
    padding-bottom: 8px;
    border-bottom: 1px solid $grey-3;
    position: relative;
    .favorite_comment {
      display: flex;
      align-items: center;
      justify-content: space-between;
      span {
        margin-left: 4px;
        font-size: 13px;
        font-weight: 700;
      }
      .favorite {
        margin-right: 8px;
      }
    }
  }
```

Id.module.scss 108Line입니다.

FavoriteCommentShare 컴포넌트를 목표 상세 보기에서 사용하려니까 스타일이 적용이 되질 않네요. 
아마 container 안에 적으셔서 그런 거 같은데..

해당 스타일을 Id.module.scss 파일 최상단으로 옮기거나, 공통 컴포넌트의 scss은 별도로 관리하는 방법이 있겠네요.
어떤 방법이 편하실까요?
